let sphere_functions=
        ["lemma_test";"log";"sin";"cos";"pi";"tan";"acs";"acos";"asn";"asin";"atn";"atan";"sqrt";"atn2";"atan2";"delta_x";"delta_y";"delta4_y";"sol_y";"dih_y";"rhazim";
        "lmfun";"lnazim";"hminus";"ly";"interp";
        "wtcount3_y";"wtcount6_y";"bump";"beta_bump_y";"matan";"sqp";"sqn";"gamma4f";"vol4f";"y_of_x";"vol_y";"rad2_y";"vol3f";"vol3r";"vol2f";"delta4_y";"delta4_squared_y";"x1_delta_y";
"gamma3f";"gamma23f";
"gamma23f_red_03";"gamma23f_126_03";
"quadratic_root_plus";"REAL_MUL_LZERO";"abc_of_quadratic";
"REAL_MUL_RZERO";"pathL";"pathR";"node2_y";"node3_y";
"rhazim2";"rhazim3";"rhazim_x";"rhazim2_x";"rhazim3_x";
"rotate2";"rotate3";"rotate4";"rotate5";"rotate6";
"sol_euler345_x_div_sqrtdelta";
"sol_euler156_x_div_sqrtdelta";
"sol_euler246_x_div_sqrtdelta";
"ldih_x_div_sqrtdelta_posbranch";
"ldih2_x_div_sqrtdelta_posbranch";
"ldih2_x_div_sqrtdelta_posbranch";
"ldih3_x_div_sqrtdelta_posbranch";
"ldih5_x_div_sqrtdelta_posbranch";
"ldih6_x_div_sqrtdelta_posbranch";
"lmdih_x_div_sqrtdelta_posbranch";
"lmdih2_x_div_sqrtdelta_posbranch";
"lmdih3_x_div_sqrtdelta_posbranch";
"lmdih5_x_div_sqrtdelta_posbranch";
"lmdih6_x_div_sqrtdelta_posbranch";
"taum_x";
"edge_flat2_x";
"delta_template_B_x";
"dih_hexall_x";
"dih1_hexall_x";
"upper_dih_hexall_x";
"delta_hexall_x";
"delta4_hexall_x";
"taum_hexall_x";
"eulerA_hexall_x";
"factor345_hexall_x";
"law_cosines_234_x";
"law_cosines_126_x";
"delta_126_x";
"taum_template_B_x";
"dih_template_B_x";
"upper_dih_y";
"gamma3f_135_n";"gamma3f_126_n";"gamma23f_n";"gamma23f_126_03_n";"h0";"sol0";"tau0";"hplus";"mm1";"mm2";"vol_x";"sqrt8";"sqrt2";"sqrt3";"rho";"rho_x";
"rad2_x";"ups_x";"eta_x";"eta_y";"volR"; (* solRy";"dihRy";" *)
"norm2hh";"arclength";
"beta_bump_force_y";"a_spine5";"b_spine5";"beta_bump_lb";"marchal_quartic";"vol2r";
"tame_table_d";"delta_x4";"dih_x";"delta4_squared_x";"x1_delta_x";"quad_root_plus_curry";
"edge_flat";"const1";"taum";"flat_term";"lfun";
"taum_y1";"taum_y2";"taum_y1_y2";"arclength_y1";"arclength_y2";"arc_hhn";"asn797k";"asnFnhk";
"lfun_y1";"arclength_x_123";"arclength_x_345";"acs_sqrt_x1_d4";"acs_sqrt_x2_d4";"critical_edge_y";
"tauq";"enclosed";"sol_euler_x_div_sqrtdelta";"dih_x_div_sqrtdelta_posbranch";"surfR";"surfRy";"surfRdyc2";"surfy";"dih2_y";"dih3_y";"dih4_y";"dih5_y";"dih6_y";"dih2_x";"dih3_x";
"num1";"num2";"num_combo1";"rat1";"rat2";"flat_term_x";"upper_dih_x";"eulerA_x";"delta_234_x";"gamma4fgcy";
"cayleyR";"muR";"enclosed"
]
;;
let bounds_templates = [
"dart_std4";"dart4_diag3_b";"dart_std3";"dartX";"dartY";"dart4_diag3";"apex_flat";"apex_flat_modified"; "apex_A";"dart_std3_small";"dart_std3_big";"dart_std3_mini";              "apex_sup_flat";"apex_flat_hll";"dart_std3_big_200_218";"apex_std3_hll";"apex_std3_lhh";"apex_std3_small_hll";"dart_mll_w";"dart_mll_n";"dart_Hll_n";"dart_Hll_w";"dart_std3_lw";      "apex_flat_l";"apex_flat_h";"apex_std3_lll_xww";"apex_std3_lll_wxx"
];;
